# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yoseph Wijaya Savianto
email: info@yoseph.ws
description: > # this means to ignore newlines until "baseurl:"
  Hello my name is Yoseph Wijaya Savianto, Very introvert person but love to
  share everything for unique and original people, to know more about me you
  can add and drop me chat on whatsapp.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: > #
  © Copyright 2017 [yoseph.ws](https://yoseph.ws)
  — Collaboration with [wijaya.cc](https://wijaya.cc)
twitter_username: jekyllrb
github_username:  jekyll
repository: nsnull0/meself

# Build settings
# theme: minima
sass:
  style: compressed
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
#
limit_posts: 12
permalink: pretty
show_drafts: true
unpublished: true
future: true
