# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
baseurl:      "" # the subpath of your site, e.g. /blog
url:          "" # the base hostname & protocol for your site, e.g. http://example.com
title:        Yoseph Wijaya Savianto
email:        info@yoseph.ws
description:  >
  Hello my name is Yoseph Wijaya Savianto, Very introvert person but love to
  share everything for unique and original people, to know more about me you
  can add and drop me chat on whatsapp.
copyright:    >
  © Copyright 2021 [ME.SELF](http://yoseph.ws)
repository:   nsnull0/meself
########################################
permalink:    pretty
limit_posts:  12
show_drafts:  true
unpublished:  true
future:       true
########################################
defaults:
  - ####################################
    scope: { path: "" }
    values:
      layout: page
      author: Yoseph Wijaya Savianto
  - ####################################
    scope: { path: _posts }
    values: { layout: post }
  - ####################################
    scope: { path: _drafts }
    values: { layout: post }
########################################
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
########################################
sass:
  style: compressed
########################################
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
########################################