name: Jekyll Deploy

on:
  push:
    branches:
    - yy/gatest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add secrets
        run: ./prescript.sh {{ secrets.GIT_TOKEN_MAPBOX }} {{ secrets.SLACK_URL_WEBHOOK }} {{ secrets.GIT_URL_GOOGLE_MAPS }}

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/gems
          key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build & Deploy to GitHub Pages
        uses: DavidS/jekyll-deploy@main
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}